### ISSUE TITLE
use case data not found

### ISSUE THREAD

**Issue by Elisa89m** [sidhomj/DeepTCR_Cancer#1]
Hi, 

I'm trying to use DeepTCR_cancer and I noticed that some script call data from directory "Data/bulk_tcr"  but in the material provided there isn't "bulk_tcr" folder.

Can you please add this material or  explain me the reason why it is not present?

Thank you in advance.

Elisa

**Comment by sidhomj** [comment]
The raw/bulk TCR data is not available for this manuscript due to it being protected under the clinical trial.
